workflows:
  ios-workflow:
    name: Ionic Capacitor iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m2

    environment:
      node: 18
      xcode: latest

    scripts:
      - name: Install dependencies
        script: npm install

      - name: Build web app
        script: npm run build

      - name: Sync Capacitor
        script: npx cap sync ios

      - name: Build iOS app
        script: |
          cd ios/App
          xcodebuild -workspace App.xcworkspace \
                     -scheme App \
                     -configuration Release \
                     -sdk iphoneos \
                     archive -archivePath $CM_BUILD_DIR/App.xcarchive

    artifacts:
      - build/ios/ipa/*.ipa
      - ios/App/build/**/*.ipa
