workflows:
  ios-workflow:
    name: Ionic Capacitor iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m2

    environment:
      node: 18
      xcode: latest
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.shadangakriya.app

    scripts:
      - name: Install dependencies
        script: |
          cd client
          npm install

      - name: Build React app
        script: |
          cd client
          npm run build

      - name: Sync Capacitor iOS
        script: |
          cd client
          npx cap sync ios

      - name: Set up code signing
        script: |
          xcode-project use-profiles

      - name: Build IPA
        script: |
          cd client
          xcode-project build-ipa \
            --workspace ios/App/App.xcworkspace \
            --scheme App

    artifacts:
      - client/build/ios/ipa/*.ipa