workflows:
  ios-workflow:
    name: Ionic Capacitor iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m2

    environment:
      node: 18
      xcode: latest

    scripts:
      - name: Install dependencies (client)
        script: |
          cd client
          npm install

      - name: Build React app
        script: |
          cd client
          npm run build

      - name: Sync Capacitor iOS
        script: |
          cd client
          npx cap sync ios

      - name: Build iOS
        script: |
          cd client/ios/App
          xcodebuild -workspace App.xcworkspace \
                     -scheme App \
                     -configuration Release \
                     -sdk iphoneos \
                     archive -archivePath $CM_BUILD_DIR/App.xcarchive

    artifacts:
      - client/ios/App/build/**/*.ipa
      - build/ios/ipa/*.ipa
